CREATE DATABASE TickEx;

CREATE TABLE KORISNIK
(
  idKor SERIAL,
  email VARCHAR(320) NOT NULL,
  PRIMARY KEY (idKor),
  UNIQUE (email)
);

CREATE TABLE VRSTA_DOGAĐAJA
(
  idDog SERIAL,
  nazVrDos VARCHAR(50) NOT NULL,
  PRIMARY KEY (idDog)
);

CREATE TABLE OGLAS
(
  idOgl SERIAL,
  nazDog VARCHAR(50) NOT NULL,
  mjesto VARCHAR(50) NOT NULL,
  datum DATE NOT NULL,
  brSje INT,
  vrsUla VARCHAR(50),
  status BOOLEAN DEFAULT FALSE NOT NULL, /*false znaci da jos nije prodan */
  cijena INT NOT NULL,
  idProdavac INT NOT NULL,
  idDog INT NOT NULL,
  PRIMARY KEY (idOgl),
  FOREIGN KEY (idProdavac) REFERENCES KORISNIK(idKor),
  FOREIGN KEY (idDog) REFERENCES VRSTA_DOGAĐAJA(idDog)
);



